import { Geist, Geist_Mono , Glory } from "next/font/google";
import "./globals.css"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const glory = Glory({
  variable: "--font-glory",
  subsets: ["latin"],
});

export const metadata = {
  title: "South City Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${glory.variable} h-full antialiased`}
    >
      <head>
        <script async src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
